### ISSUE TITLE
Tutorial Scene - Skip Tutorial 

### ISSUE THREAD

**Issue by rgiles4** [COS420-Fall23/Team-H#27]
User Story: As a user familiar with VR, I want to hide or skip tutorials, to jump into the experience immediately.

Completed when:  After entering the tutorial scene, the player is presented with the option to skip the tutorial. Skipping the tutorial brings the user back to the Main Menu Scene.

**Comment by MattsWhatChuGet** [comment]
Perhaps have the Tutorial be a Button on the main menu.
