### ISSUE TITLE
Product Backlog

### ISSUE THREAD

**Issue by ZachWilliams83** [COS420-Fall23/Team-H#7]
Product backlog and sprint backlog should match i.e. product backlog items in the sprint backlog need to have the same IDs etc. If they do not match deduct -2 points.

Make sure that all of your user stories are in the product backlog. For any missing user story deduct -1 point.

All columns based on the projects’ details document should be in the product backlog and must be filled out. For any missing column or missing information deduct -2 points.

**Comment by MattsWhatChuGet** [comment]
[This is the Google Doc for the Product Log template.](https://docs.google.com/spreadsheets/d/1h7aVo1XzzB8HKicHq3lfPEFbXFn8RDbz/edit?usp=sharing&ouid=115618816157023033572&rtpof=true&sd=true)
